# Generated by Django 5.0.3 on 2024-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hello", "0002_user_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("feedback", models.TextField()),
            ],
        ),
    ]
